package manager.geocoding;

/**
 * Interface used for the geocoding of strings that are assumed to be city, city districts, countries, region.
 */
public interface Geocoder {

    /**
     * This method is the one used to get the location bound to the given name
     * @param query The string representing the location to be found
     * @return The FoundLocation generated by the query
     * @see FoundLocation
     */
    FoundLocation getLocation(String query);

}
